<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DepartmentExamBank;

class DepartmentExamBankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            // Programming Fundamentals (20 questions)
            [
                'question' => 'What does HTML stand for?',
                'option1' => 'Hyper Text Markup Language',
                'option2' => 'High Tech Modern Language',
                'option3' => 'Home Tool Markup Language',
                'option4' => 'Hyperlinks and Text Markup Language',
                'correct_answer' => '1',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'Which programming language is known as the "language of the web"?',
                'option1' => 'Python',
                'option2' => 'Java',
                'option3' => 'JavaScript',
                'option4' => 'C++',
                'correct_answer' => '3',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'What is a variable in programming?',
                'option1' => 'A fixed value that cannot change',
                'option2' => 'A container for storing data values',
                'option3' => 'A type of loop',
                'option4' => 'A programming error',
                'correct_answer' => '2',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'Which symbol is used for comments in Python?',
                'option1' => '//',
                'option2' => '/* */',
                'option3' => '#',
                'option4' => '<!--',
                'correct_answer' => '3',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'What does CSS stand for?',
                'option1' => 'Computer Style Sheets',
                'option2' => 'Cascading Style Sheets',
                'option3' => 'Creative Style Sheets',
                'option4' => 'Colorful Style Sheets',
                'correct_answer' => '2',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'Which data type is used to store true or false values?',
                'option1' => 'Integer',
                'option2' => 'String',
                'option3' => 'Boolean',
                'option4' => 'Float',
                'correct_answer' => '3',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'What is an algorithm?',
                'option1' => 'A programming language',
                'option2' => 'A step-by-step procedure to solve a problem',
                'option3' => 'A type of software',
                'option4' => 'A computer virus',
                'correct_answer' => '2',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'Which loop executes at least once regardless of the condition?',
                'option1' => 'for loop',
                'option2' => 'while loop',
                'option3' => 'do-while loop',
                'option4' => 'foreach loop',
                'correct_answer' => '3',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'What is the purpose of an if statement?',
                'option1' => 'To repeat code multiple times',
                'option2' => 'To make decisions in code',
                'option3' => 'To declare variables',
                'option4' => 'To end a program',
                'correct_answer' => '2',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'What does API stand for?',
                'option1' => 'Application Programming Interface',
                'option2' => 'Advanced Programming Integration',
                'option3' => 'Automated Program Instruction',
                'option4' => 'Application Process Integration',
                'correct_answer' => '1',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'Which of the following is NOT a programming paradigm?',
                'option1' => 'Object-Oriented Programming',
                'option2' => 'Functional Programming',
                'option3' => 'Procedural Programming',
                'option4' => 'Circular Programming',
                'correct_answer' => '4',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'What is the output of 5 + 3 * 2?',
                'option1' => '16',
                'option2' => '11',
                'option3' => '13',
                'option4' => '10',
                'correct_answer' => '2',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'Which operator is used for string concatenation in most languages?',
                'option1' => '-',
                'option2' => '+',
                'option3' => '*',
                'option4' => '/',
                'correct_answer' => '2',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'What is an array?',
                'option1' => 'A single value variable',
                'option2' => 'A collection of similar data types',
                'option3' => 'A function',
                'option4' => 'A loop structure',
                'correct_answer' => '2',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'Which keyword is used to define a function in Python?',
                'option1' => 'function',
                'option2' => 'func',
                'option3' => 'def',
                'option4' => 'define',
                'correct_answer' => '3',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'What does IDE stand for?',
                'option1' => 'Integrated Development Environment',
                'option2' => 'Internet Development Engine',
                'option3' => 'Interactive Design Environment',
                'option4' => 'Intelligent Development Editor',
                'correct_answer' => '1',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'Which is a valid variable name in most programming languages?',
                'option1' => '2variable',
                'option2' => 'variable-name',
                'option3' => 'variable_name',
                'option4' => 'variable name',
                'correct_answer' => '3',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'What is debugging?',
                'option1' => 'Writing code',
                'option2' => 'Finding and fixing errors in code',
                'option3' => 'Running a program',
                'option4' => 'Compiling code',
                'correct_answer' => '2',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'Which symbol represents assignment in most programming languages?',
                'option1' => '==',
                'option2' => '=',
                'option3' => ':=',
                'option4' => '<=',
                'correct_answer' => '2',
                'category' => 'Programming Fundamentals',
            ],
            [
                'question' => 'What is the first index of an array in most programming languages?',
                'option1' => '1',
                'option2' => '0',
                'option3' => '-1',
                'option4' => '10',
                'correct_answer' => '2',
                'category' => 'Programming Fundamentals',
            ],

            // Database Management (20 questions)
            [
                'question' => 'What does SQL stand for?',
                'option1' => 'Structured Query Language',
                'option2' => 'Simple Query Language',
                'option3' => 'Standard Question Language',
                'option4' => 'System Query Language',
                'correct_answer' => '1',
                'category' => 'Database Management',
            ],
            [
                'question' => 'Which SQL command is used to retrieve data from a database?',
                'option1' => 'GET',
                'option2' => 'SELECT',
                'option3' => 'FETCH',
                'option4' => 'RETRIEVE',
                'correct_answer' => '2',
                'category' => 'Database Management',
            ],
            [
                'question' => 'What is a primary key?',
                'option1' => 'A key that opens the database',
                'option2' => 'A unique identifier for a record',
                'option3' => 'The first column in a table',
                'option4' => 'A password for the database',
                'correct_answer' => '2',
                'category' => 'Database Management',
            ],
            [
                'question' => 'Which command is used to add new data to a database?',
                'option1' => 'ADD',
                'option2' => 'INSERT',
                'option3' => 'APPEND',
                'option4' => 'CREATE',
                'correct_answer' => '2',
                'category' => 'Database Management',
            ],
            [
                'question' => 'What does CRUD stand for?',
                'option1' => 'Create, Read, Update, Delete',
                'option2' => 'Control, Run, Update, Deploy',
                'option3' => 'Create, Refresh, Upload, Download',
                'option4' => 'Copy, Read, Update, Delete',
                'correct_answer' => '1',
                'category' => 'Database Management',
            ],
            [
                'question' => 'Which clause is used to filter results in SQL?',
                'option1' => 'FILTER',
                'option2' => 'WHERE',
                'option3' => 'HAVING',
                'option4' => 'IF',
                'correct_answer' => '2',
                'category' => 'Database Management',
            ],
            [
                'question' => 'What is a foreign key?',
                'option1' => 'A key from another country',
                'option2' => 'A field that links to a primary key in another table',
                'option3' => 'An external database password',
                'option4' => 'A backup key',
                'correct_answer' => '2',
                'category' => 'Database Management',
            ],
            [
                'question' => 'Which SQL command is used to modify existing data?',
                'option1' => 'MODIFY',
                'option2' => 'CHANGE',
                'option3' => 'UPDATE',
                'option4' => 'ALTER',
                'correct_answer' => '3',
                'category' => 'Database Management',
            ],
            [
                'question' => 'What is normalization in databases?',
                'option1' => 'Making all values the same',
                'option2' => 'Organizing data to reduce redundancy',
                'option3' => 'Deleting unnecessary data',
                'option4' => 'Encrypting the database',
                'correct_answer' => '2',
                'category' => 'Database Management',
            ],
            [
                'question' => 'Which command is used to remove data from a database?',
                'option1' => 'REMOVE',
                'option2' => 'DROP',
                'option3' => 'DELETE',
                'option4' => 'ERASE',
                'correct_answer' => '3',
                'category' => 'Database Management',
            ],
            [
                'question' => 'What does DBMS stand for?',
                'option1' => 'Database Management System',
                'option2' => 'Data Backup Management System',
                'option3' => 'Digital Base Management Software',
                'option4' => 'Database Monitoring System',
                'correct_answer' => '1',
                'category' => 'Database Management',
            ],
            [
                'question' => 'Which SQL clause is used to sort results?',
                'option1' => 'SORT',
                'option2' => 'ORDER BY',
                'option3' => 'GROUP BY',
                'option4' => 'ARRANGE',
                'correct_answer' => '2',
                'category' => 'Database Management',
            ],
            [
                'question' => 'What is a JOIN in SQL?',
                'option1' => 'Combining two databases',
                'option2' => 'Combining rows from two or more tables',
                'option3' => 'Creating a new table',
                'option4' => 'Deleting duplicate records',
                'correct_answer' => '2',
                'category' => 'Database Management',
            ],
            [
                'question' => 'Which is NOT a type of SQL JOIN?',
                'option1' => 'INNER JOIN',
                'option2' => 'OUTER JOIN',
                'option3' => 'CROSS JOIN',
                'option4' => 'PARALLEL JOIN',
                'correct_answer' => '4',
                'category' => 'Database Management',
            ],
            [
                'question' => 'What is an index in a database?',
                'option1' => 'The first record',
                'option2' => 'A data structure that improves query speed',
                'option3' => 'A table of contents',
                'option4' => 'A backup file',
                'correct_answer' => '2',
                'category' => 'Database Management',
            ],
            [
                'question' => 'Which SQL function returns the number of rows?',
                'option1' => 'SUM()',
                'option2' => 'TOTAL()',
                'option3' => 'COUNT()',
                'option4' => 'NUMBER()',
                'correct_answer' => '3',
                'category' => 'Database Management',
            ],
            [
                'question' => 'What is a transaction in database terms?',
                'option1' => 'A database purchase',
                'option2' => 'A sequence of operations performed as a single unit',
                'option3' => 'A data exchange',
                'option4' => 'A table relationship',
                'correct_answer' => '2',
                'category' => 'Database Management',
            ],
            [
                'question' => 'Which SQL keyword is used to eliminate duplicate rows?',
                'option1' => 'UNIQUE',
                'option2' => 'DISTINCT',
                'option3' => 'DIFFERENT',
                'option4' => 'SINGLE',
                'correct_answer' => '2',
                'category' => 'Database Management',
            ],
            [
                'question' => 'What does ACID stand for in database transactions?',
                'option1' => 'Atomicity, Consistency, Isolation, Durability',
                'option2' => 'Access, Control, Integration, Data',
                'option3' => 'Automated, Centralized, Integrated, Database',
                'option4' => 'Advanced, Computed, Indexed, Data',
                'correct_answer' => '1',
                'category' => 'Database Management',
            ],
            [
                'question' => 'Which database is an example of a relational database?',
                'option1' => 'MongoDB',
                'option2' => 'MySQL',
                'option3' => 'Redis',
                'option4' => 'Cassandra',
                'correct_answer' => '2',
                'category' => 'Database Management',
            ],

            // Networking (15 questions)
            [
                'question' => 'What does IP stand for?',
                'option1' => 'Internet Protocol',
                'option2' => 'Internal Process',
                'option3' => 'Information Program',
                'option4' => 'Interactive Protocol',
                'correct_answer' => '1',
                'category' => 'Networking',
            ],
            [
                'question' => 'Which port number is typically used for HTTP?',
                'option1' => '21',
                'option2' => '80',
                'option3' => '443',
                'option4' => '22',
                'correct_answer' => '2',
                'category' => 'Networking',
            ],
            [
                'question' => 'What does DNS stand for?',
                'option1' => 'Domain Name System',
                'option2' => 'Digital Network Service',
                'option3' => 'Data Network System',
                'option4' => 'Domain Network Server',
                'correct_answer' => '1',
                'category' => 'Networking',
            ],
            [
                'question' => 'Which protocol is used for secure web browsing?',
                'option1' => 'HTTP',
                'option2' => 'FTP',
                'option3' => 'HTTPS',
                'option4' => 'SMTP',
                'correct_answer' => '3',
                'category' => 'Networking',
            ],
            [
                'question' => 'What is the maximum number of hosts in a Class C IP network?',
                'option1' => '256',
                'option2' => '254',
                'option3' => '255',
                'option4' => '128',
                'correct_answer' => '2',
                'category' => 'Networking',
            ],
            [
                'question' => 'Which device connects multiple networks together?',
                'option1' => 'Hub',
                'option2' => 'Switch',
                'option3' => 'Router',
                'option4' => 'Modem',
                'correct_answer' => '3',
                'category' => 'Networking',
            ],
            [
                'question' => 'What does MAC address stand for?',
                'option1' => 'Machine Access Control',
                'option2' => 'Media Access Control',
                'option3' => 'Master Access Code',
                'option4' => 'Mobile Access Connection',
                'correct_answer' => '2',
                'category' => 'Networking',
            ],
            [
                'question' => 'Which layer of the OSI model handles routing?',
                'option1' => 'Physical Layer',
                'option2' => 'Data Link Layer',
                'option3' => 'Network Layer',
                'option4' => 'Transport Layer',
                'correct_answer' => '3',
                'category' => 'Networking',
            ],
            [
                'question' => 'What is the purpose of a firewall?',
                'option1' => 'To increase internet speed',
                'option2' => 'To protect against unauthorized access',
                'option3' => 'To store data',
                'option4' => 'To connect to Wi-Fi',
                'correct_answer' => '2',
                'category' => 'Networking',
            ],
            [
                'question' => 'Which protocol is used for sending emails?',
                'option1' => 'HTTP',
                'option2' => 'FTP',
                'option3' => 'SMTP',
                'option4' => 'POP3',
                'correct_answer' => '3',
                'category' => 'Networking',
            ],
            [
                'question' => 'What does LAN stand for?',
                'option1' => 'Large Area Network',
                'option2' => 'Local Area Network',
                'option3' => 'Long Access Network',
                'option4' => 'Limited Area Network',
                'correct_answer' => '2',
                'category' => 'Networking',
            ],
            [
                'question' => 'Which IP address is a loopback address?',
                'option1' => '192.168.1.1',
                'option2' => '127.0.0.1',
                'option3' => '10.0.0.1',
                'option4' => '172.16.0.1',
                'correct_answer' => '2',
                'category' => 'Networking',
            ],
            [
                'question' => 'What is bandwidth?',
                'option1' => 'The width of a network cable',
                'option2' => 'The maximum data transfer rate',
                'option3' => 'The number of devices connected',
                'option4' => 'The distance of network coverage',
                'correct_answer' => '2',
                'category' => 'Networking',
            ],
            [
                'question' => 'Which topology connects all devices to a central hub?',
                'option1' => 'Bus Topology',
                'option2' => 'Ring Topology',
                'option3' => 'Star Topology',
                'option4' => 'Mesh Topology',
                'correct_answer' => '3',
                'category' => 'Networking',
            ],
            [
                'question' => 'What does VPN stand for?',
                'option1' => 'Virtual Private Network',
                'option2' => 'Very Private Network',
                'option3' => 'Verified Personal Network',
                'option4' => 'Virtual Public Network',
                'correct_answer' => '1',
                'category' => 'Networking',
            ],

            // Data Structures & Algorithms (15 questions)
            [
                'question' => 'Which data structure follows LIFO principle?',
                'option1' => 'Queue',
                'option2' => 'Stack',
                'option3' => 'Array',
                'option4' => 'Tree',
                'correct_answer' => '2',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'What is the time complexity of binary search?',
                'option1' => 'O(n)',
                'option2' => 'O(n²)',
                'option3' => 'O(log n)',
                'option4' => 'O(1)',
                'correct_answer' => '3',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'Which data structure follows FIFO principle?',
                'option1' => 'Stack',
                'option2' => 'Queue',
                'option3' => 'Tree',
                'option4' => 'Graph',
                'correct_answer' => '2',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'What is a linked list?',
                'option1' => 'A static array',
                'option2' => 'A sequence of nodes where each node points to the next',
                'option3' => 'A hierarchical structure',
                'option4' => 'A sorting algorithm',
                'correct_answer' => '2',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'Which sorting algorithm has the best average-case time complexity?',
                'option1' => 'Bubble Sort',
                'option2' => 'Selection Sort',
                'option3' => 'Quick Sort',
                'option4' => 'Insertion Sort',
                'correct_answer' => '3',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'What is a binary tree?',
                'option1' => 'A tree with only two nodes',
                'option2' => 'A tree where each node has at most two children',
                'option3' => 'A tree with two roots',
                'option4' => 'A linear data structure',
                'correct_answer' => '2',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'What does Big O notation describe?',
                'option1' => 'The size of data',
                'option2' => 'The complexity of an algorithm',
                'option3' => 'The type of variable',
                'option4' => 'The programming language',
                'correct_answer' => '2',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'Which traversal visits the root node first?',
                'option1' => 'Inorder',
                'option2' => 'Preorder',
                'option3' => 'Postorder',
                'option4' => 'Level order',
                'correct_answer' => '2',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'What is a hash table?',
                'option1' => 'A sorting algorithm',
                'option2' => 'A data structure that maps keys to values',
                'option3' => 'A type of tree',
                'option4' => 'A linear search method',
                'correct_answer' => '2',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'What is recursion?',
                'option1' => 'A loop structure',
                'option2' => 'A function calling itself',
                'option3' => 'A data structure',
                'option4' => 'An error handling method',
                'correct_answer' => '2',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'Which data structure is best for implementing a priority queue?',
                'option1' => 'Array',
                'option2' => 'Linked List',
                'option3' => 'Heap',
                'option4' => 'Stack',
                'correct_answer' => '3',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'What is the worst-case time complexity of bubble sort?',
                'option1' => 'O(n)',
                'option2' => 'O(n log n)',
                'option3' => 'O(n²)',
                'option4' => 'O(log n)',
                'correct_answer' => '3',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'What is a graph in data structures?',
                'option1' => 'A chart or diagram',
                'option2' => 'A collection of nodes connected by edges',
                'option3' => 'A sorting algorithm',
                'option4' => 'A type of array',
                'correct_answer' => '2',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'Which search algorithm requires a sorted array?',
                'option1' => 'Linear Search',
                'option2' => 'Binary Search',
                'option3' => 'Sequential Search',
                'option4' => 'Jump Search',
                'correct_answer' => '2',
                'category' => 'Data Structures & Algorithms',
            ],
            [
                'question' => 'What is a doubly linked list?',
                'option1' => 'A list with two elements',
                'option2' => 'A list where nodes have pointers to both next and previous nodes',
                'option3' => 'Two separate linked lists',
                'option4' => 'A circular linked list',
                'correct_answer' => '2',
                'category' => 'Data Structures & Algorithms',
            ],

            // Web Development (15 questions)
            [
                'question' => 'What is the purpose of the <head> tag in HTML?',
                'option1' => 'To display the main content',
                'option2' => 'To contain metadata and links to resources',
                'option3' => 'To create headers',
                'option4' => 'To add images',
                'correct_answer' => '2',
                'category' => 'Web Development',
            ],
            [
                'question' => 'Which property is used to change the background color in CSS?',
                'option1' => 'color',
                'option2' => 'bgcolor',
                'option3' => 'background-color',
                'option4' => 'bg-color',
                'correct_answer' => '3',
                'category' => 'Web Development',
            ],
            [
                'question' => 'What does DOM stand for?',
                'option1' => 'Document Object Model',
                'option2' => 'Data Object Management',
                'option3' => 'Digital Online Method',
                'option4' => 'Document Oriented Model',
                'correct_answer' => '1',
                'category' => 'Web Development',
            ],
            [
                'question' => 'Which JavaScript method is used to select an element by ID?',
                'option1' => 'querySelector()',
                'option2' => 'getElementById()',
                'option3' => 'getElement()',
                'option4' => 'selectId()',
                'correct_answer' => '2',
                'category' => 'Web Development',
            ],
            [
                'question' => 'What is Bootstrap?',
                'option1' => 'A programming language',
                'option2' => 'A CSS framework',
                'option3' => 'A database',
                'option4' => 'A web server',
                'correct_answer' => '2',
                'category' => 'Web Development',
            ],
            [
                'question' => 'Which HTTP method is used to submit form data?',
                'option1' => 'GET',
                'option2' => 'POST',
                'option3' => 'PUT',
                'option4' => 'DELETE',
                'correct_answer' => '2',
                'category' => 'Web Development',
            ],
            [
                'question' => 'What is AJAX?',
                'option1' => 'A programming language',
                'option2' => 'A technique for asynchronous web requests',
                'option3' => 'A database system',
                'option4' => 'A web server',
                'correct_answer' => '2',
                'category' => 'Web Development',
            ],
            [
                'question' => 'Which tag is used to create a hyperlink in HTML?',
                'option1' => '<link>',
                'option2' => '<a>',
                'option3' => '<href>',
                'option4' => '<url>',
                'correct_answer' => '2',
                'category' => 'Web Development',
            ],
            [
                'question' => 'What is responsive web design?',
                'option1' => 'Fast loading websites',
                'option2' => 'Websites that adapt to different screen sizes',
                'option3' => 'Interactive websites',
                'option4' => 'Animated websites',
                'correct_answer' => '2',
                'category' => 'Web Development',
            ],
            [
                'question' => 'Which CSS property is used to change text size?',
                'option1' => 'text-size',
                'option2' => 'font-size',
                'option3' => 'size',
                'option4' => 'text-style',
                'correct_answer' => '2',
                'category' => 'Web Development',
            ],
            [
                'question' => 'What is jQuery?',
                'option1' => 'A CSS framework',
                'option2' => 'A JavaScript library',
                'option3' => 'A database',
                'option4' => 'A web server',
                'correct_answer' => '2',
                'category' => 'Web Development',
            ],
            [
                'question' => 'Which attribute specifies an alternative text for an image?',
                'option1' => 'title',
                'option2' => 'alt',
                'option3' => 'text',
                'option4' => 'caption',
                'correct_answer' => '2',
                'category' => 'Web Development',
            ],
            [
                'question' => 'What is the box model in CSS?',
                'option1' => 'A design pattern',
                'option2' => 'The structure of content, padding, border, and margin',
                'option3' => 'A type of container',
                'option4' => 'A layout framework',
                'correct_answer' => '2',
                'category' => 'Web Development',
            ],
            [
                'question' => 'Which JavaScript keyword is used to declare a constant?',
                'option1' => 'var',
                'option2' => 'let',
                'option3' => 'const',
                'option4' => 'constant',
                'correct_answer' => '3',
                'category' => 'Web Development',
            ],
            [
                'question' => 'What is Node.js?',
                'option1' => 'A JavaScript runtime environment',
                'option2' => 'A CSS preprocessor',
                'option3' => 'A database',
                'option4' => 'A text editor',
                'correct_answer' => '1',
                'category' => 'Web Development',
            ],

            // Software Engineering (15 questions)
            [
                'question' => 'What is the Agile methodology?',
                'option1' => 'A programming language',
                'option2' => 'An iterative approach to software development',
                'option3' => 'A database management system',
                'option4' => 'A testing tool',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What does SDLC stand for?',
                'option1' => 'Software Development Life Cycle',
                'option2' => 'System Design Life Cycle',
                'option3' => 'Software Design Language Compiler',
                'option4' => 'System Development Language Code',
                'correct_answer' => '1',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What is version control?',
                'option1' => 'Software versioning',
                'option2' => 'Managing changes to source code over time',
                'option3' => 'Controlling software releases',
                'option4' => 'Testing different versions',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'Which is a popular version control system?',
                'option1' => 'Git',
                'option2' => 'HTTP',
                'option3' => 'SQL',
                'option4' => 'FTP',
                'correct_answer' => '1',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What is unit testing?',
                'option1' => 'Testing the entire system',
                'option2' => 'Testing individual components or functions',
                'option3' => 'User acceptance testing',
                'option4' => 'Performance testing',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What is a software requirement?',
                'option1' => 'A bug in the software',
                'option2' => 'A description of what the software should do',
                'option3' => 'A programming tool',
                'option4' => 'A testing method',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What is refactoring?',
                'option1' => 'Adding new features',
                'option2' => 'Restructuring code without changing its behavior',
                'option3' => 'Fixing bugs',
                'option4' => 'Deleting old code',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What is continuous integration (CI)?',
                'option1' => 'A programming paradigm',
                'option2' => 'Automatically testing and merging code changes',
                'option3' => 'A deployment strategy',
                'option4' => 'A database technique',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What is a design pattern?',
                'option1' => 'A UI/UX template',
                'option2' => 'A reusable solution to common software problems',
                'option3' => 'A coding style',
                'option4' => 'A testing framework',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What is the Waterfall model?',
                'option1' => 'An iterative development approach',
                'option2' => 'A sequential software development process',
                'option3' => 'A testing methodology',
                'option4' => 'A deployment strategy',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What is a sprint in Agile?',
                'option1' => 'A fast coding session',
                'option2' => 'A time-boxed iteration for development',
                'option3' => 'A testing phase',
                'option4' => 'A deployment cycle',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What is technical debt?',
                'option1' => 'Money owed to developers',
                'option2' => 'The cost of rework caused by choosing quick solutions',
                'option3' => 'Software licensing fees',
                'option4' => 'Server hosting costs',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What is a code review?',
                'option1' => 'Checking code for errors automatically',
                'option2' => 'Examining code by other developers',
                'option3' => 'Running performance tests',
                'option4' => 'Deploying code to production',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What is DevOps?',
                'option1' => 'A programming language',
                'option2' => 'A practice combining development and operations',
                'option3' => 'A testing tool',
                'option4' => 'A database system',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
            [
                'question' => 'What is regression testing?',
                'option1' => 'Testing new features only',
                'option2' => 'Re-testing to ensure changes haven\'t broken existing functionality',
                'option3' => 'Performance testing',
                'option4' => 'Security testing',
                'correct_answer' => '2',
                'category' => 'Software Engineering',
            ],
        ];

        // Add common fields to all questions
        foreach ($questions as &$question) {
            $question['department'] = 'BSIT';
            $question['status'] = '1';
            $question['question_formatted'] = null;
            $question['option1_formatted'] = null;
            $question['option1_image'] = null;
            $question['option2_formatted'] = null;
            $question['option2_image'] = null;
            $question['option3_formatted'] = null;
            $question['option3_image'] = null;
            $question['option4_formatted'] = null;
            $question['option4_image'] = null;
            $question['option5'] = null;
            $question['option5_formatted'] = null;
            $question['option5_image'] = null;
            $question['image'] = null;
            $question['direction'] = null;
            $question['created_at'] = now();
            $question['updated_at'] = now();
        }

        DepartmentExamBank::insert($questions);

        $this->command->info('Successfully seeded 100 BSIT questions in department_exam_bank table!');
    }
}

